#!/bin/bash
set -Eeuxo pipefail

OUTPUT=minified
mkdir -p -v $OUTPUT/font
cp font/* $OUTPUT/font

uglifyjs dome.js > $OUTPUT/dome.js
csso style.css > $OUTPUT/style.css
html-minifier --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true index.html > $OUTPUT/index.html